name: "Omochice/action-normalized-vim-plugin-name"
description: "Provide normalized vim plugin name"
author: "Omochice"

# Metadata for market place
branding:
  icon: "activity"
  color: "blue"

# Define your inputs here.
inputs:
  trim-tail-dot-vim:
    description: "Whether trim tail '.vim' pattern"
    required: false
    default: "false"

# Define your outputs here.
outputs:
  normalizedName:
    description: 'Normalized plugin name'

runs:
  using: node20
  main: dist/main.js
